### ISSUE TITLE
make logging output configurable

### ISSUE THREAD

**Issue by ithinkispider** [mobilcom-debitel/got-swag#13]
The Standard Output of a (successful) monkeytest does not neccessarily need the full list of all requests tested. Sommetimes you only need a simple OK (no http4** or http5** Status found).

On other hands in case of on error there might be the need of an explicit log level.
So it would be nice to have configurable log levels.

**Comment by morris** [comment]
Done. Monkey tests only dump the last request now; if you need more data add the trace option (`-T` or `--trace`) :beers:

**Comment by morris** [comment]
Test
