### ISSUE TITLE
Feature request: expose byteLength in sandbox

### ISSUE THREAD

**Issue by nicoabie** [mobilcom-debitel/got-swag#20]
First of all, this library rocks!!!

I'm having a use case on which I need to calculate the Content-Length manually.

Buffer.byteLenth would be the solution :)

I played with the source code, exposed it as parse or stringify methods and it works like a charm.
If I make a pull request would you include it?

Thanks in advance

**Comment by agpelliza** [comment]
@nicoabie you should probably send the PR with your changes to better expose your case. Also, make sure to update the README with the new interface.

**Comment by FrederikPriede** [comment]
Thx for contributing to this awesome tool! since i merged your pull request, i will close this issue now.
