### ISSUE TITLE
Not able to install got-swag

### ISSUE THREAD

**Issue by pradeepYogesh** [mobilcom-debitel/got-swag#4]
Following is the error log. Please help

---------------------------------------------------------------------------------
udo npm install got-swag -g .
npm ERR! addLocal Could not install .
npm ERR! Error: ENOENT, open 'package.json'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.19.0-59-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "got-swag" "-g" "."
npm ERR! cwd /home/pradeep/Documents/swagger-tester
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! path package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pradeep/Documents/swagger-tester/npm-debug.log
npm ERR! not ok code 0

**Comment by morris** [comment]
Hi @pradeepYogesh, thanks for reaching out. Looks like you're using Node.js v0.10, which is not supported. Please look for v6 at https://nodejs.org/en/

**Comment by morris** [comment]
I'm closing this for now as I'm pretty sure this is related to an unsupported version of Node.js. Feel free to reopen if the issue persists.
